feat: New resource for standalone project users and groups
jfrog/terraform-provider-project pull request #100
Opened 2024-02-27 14:54 UTC by Danielku15

This PR superceeds #99 with the capabilitiy to both add users and groups individually to projects. 

This way we cover both issues #98 and #83 in one go. 

## project_user
It adds a new dedicated resource which allows managing project members without touching the project itself. In our Company-wide Artifactory instance we are given 1 project by the admins and the project is mostly readonly. We can add members and manage repositories but nothing else. 

With this resource we can:

1. Add new project members to the existing project without touching it. 
2. We can still manage some memberships manually without interference with the terraform state.
3. We can auto-generate a list of users who should have theoretically access IF the accounts exist and still apply without errors (only warnings). This serves the use case where we have a central list of developers and we don't know if they already have an account in artifactory (e.g. missing SSO login). We will see who is missing a user without failing to apply users who have one. 

Unfortunately I cannot run the tests on our company artifactory instance due to permissions. But I tried to prepare already some tests. Any help in finalizing the tests is appreciated (providing an artifactory for testing or taking over to write the tests). 

I made some manual tests by using the locally compiled provider and creating members in our project. 

## project_group

Similar like project_user just simplified settings (no ignore missing feature needed here). I couldn't do proper tests in our artifactory instance as we cannot manage groups and no test data is suitable.

2024-02-27 18:22 UTC, alexhung requested changes
Look good overall. I have a few comments on test configurations dependencies, and test checks. 

We also need to bump the `project` schema version and add new attribute similar to `roles` to ease migration to use the new `project_user` and project_group` attributes: https://github.com/jfrog/terraform-provider-project/blob/master/pkg/project/resource_project.go#L266 At the very least we need deprecation messages to warn users of the new attributes.

2024-02-27 18:22 UTC, alexhung commented on pkg/project/resource_project_group_test.go
> +				project.{{ .project_name }}
This is not necessary if you have `project_key = project.{{ .project_name }}.key` as Terraform will figure out the dependency tree.

2024-02-27 18:22 UTC, alexhung commented on pkg/project/resource_project_group_test.go
> +			name = "{{ .group }}"
If you use `name = artifactory_group.{{ .group }}.name` then you won't need the `depends_on` in `project` resource.

2024-02-27 18:22 UTC, alexhung commented on pkg/project/resource_project_group_test.go
> +	group := "group1"
We should randomize the group name

2024-02-27 18:22 UTC, alexhung commented on pkg/project/resource_project_group_test.go
> +					resource.TestCheckResourceAttr(resourceName, "ignore_missing_user", "false"),
This is invalid test check. Group doesn't have this attribute 😄

2024-02-27 18:22 UTC, alexhung commented on pkg/project/resource_project_user_test.go
> +	username := "user1"
Let's randomize the user name.

2024-02-28 09:52 UTC, Danielku15 commented
Thanks for the remarks. I'm still quite new to developing Go and terraform providers 😁 

If there is some good way for me to run the test suite on my side I'm happy to do so. It's a bit unfortunate that there is no easy to use test environment due to license needs. 

Would be nice if there would be an Artifactory docker image which works for a limited time before it shuts down for such testing purposes. I'm thinking of a built-in 1hour trial with full data-loss (to prevent misuse). 😆

2024-02-28 22:11 UTC, alexhung commented
If there is some good way for me to run the test suite on my side I'm happy to do so. It's a bit unfortunate that there is no easy to use test environment due to license needs.

@Danielku15 A contributor in https://github.com/jfrog/vault-plugin-secrets-artifactory uses the JFrog JCR Docker image to test against. It doesn't require license but I'm pretty sure there are feature limitations.

Case c) is what I'd like to see. Setting `Deprecate` string **does not** actually remove the attribute or change the state. It simply makes Terraform CLI to emit that message during use to warn users about the deprecation. If you don't feel comfortable setting it, I will after this PR is merged 😄

2024-02-28 22:38 UTC, alexhung approved these changes
LGTM

2024-02-28 23:25 UTC, danielmkn approved these changes

2024-02-29 17:25 UTC, alexhung approved these changes
Looks good. I can take over from here.

2024-02-29 17:27 UTC, alexhung commented
> JFrog might consider making rather 1 provider per "API" with 1:1 mapping for resources as things are a bit inconsistent.

@Danielku15 We are working on improving the Projects API so the dependency on Artifactory API will be removed.

2024-03-01 18:59 UTC, merged