Project Key Validation fixed
jfrog/terraform-provider-project pull request #25
Opened 2022-03-22 21:48 UTC by dasmanas

closes #22 
Project key validation is fixed as per latest Artifactory release version.

2022-03-22 21:57 UTC, maheshjfrog submitted a review, later dismissed

2022-03-22 22:55 UTC, chb0github approved these changes

2022-03-22 23:18 UTC, danielmkn commented on pkg/projects/resource_project_test.go
> +				Check: resource.ComposeTestCheckFunc(
please run `make fmt`, it will fix such issues with formatting

2022-03-22 23:18 UTC, danielmkn commented on pkg/projects/validators.go
>  	"github.com/gorhill/cronexpr"
same here. `make fmt` will also sort the imports

2022-03-22 23:19 UTC, danielmkn commented on pkg/projects/validators.go
> +	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
same here. make fmt will also sort the imports

2022-03-22 23:19 UTC, danielmkn requested changes
Please run `make fmt`

2022-03-23 00:32 UTC, danielmkn approved these changes

2022-03-23 00:58 UTC, chb0github approved these changes

2022-03-23 07:24 UTC, merged

2022-04-12 09:56 UTC, martinm82 commented on pkg/projects/resource_project.go
> +			Description:      "The Project Key is added as a prefix to resources created within a Project. This field is mandatory and supports only 3 - 6 lowercase alphanumeric characters. Must begin with a
This should be updated to 3 - 10, right?